apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-todo-pv

spec:
  storageClassName: standard-retain
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
