apiVersion: v1
kind: Service
metadata:
  name: go-todo-svc
  namespace: go-todo
  labels:
    app: go-todo
    tier: application
spec:
  type: NodePort
  selector:
    app: go-todo
    tier: application
  ports:
    - port: 8000
      targetPort: 9000
